import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrimarySearchAppBar from "@/components/layout/top.tsx";
import { ThemeContextProvider } from "@/components/providers/theme.tsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <PrimarySearchAppBar />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
